### PR TITLE
Distinguish between location services disabled in the settings and location services in the application

### PR DESCRIPTION
**Pull request by KhanFu**
Created two methods `locationServicesEnabled` and `applicationLocationAuthorizationEnabled` to distinguish between when the user has location services disabled in general for their device and when they've authorized the application to use location services.

### CODE REVIEW

**Comment by GabrielCartier** [comment]
Worked with @KhanFu on this. We kept the old method for legacy purpose, but I believe some people (like we had to) would like to know either you had simply not authorized the app versus your location services are turned off.

**Comment by smileyborg** [comment]
Hey @KhanFu & @GabrielCartier, thanks again for the PR!

I just merged #27 in. Now I'm looking at this one, and from what I see, this is strictly some refactoring of the internal code with no functional changes. I don't see any case where the result of calling `locationServicesAvailable` will have changed. Is that right?

If so, can you share the rationale behind introducing the 2 private helper methods here? I could understand if you intended to expose them as public API (to let the consumer of this component call them separately), however as currently written I'm not sure what the goal behind this change is.

Thanks!

**Comment by GabrielCartier** [comment]
I think it was a bad commit, yes the goal was to add the methods to the public API. I'll check with @KhanFu and we'll push another version.

sorry our bad.

**Comment by KhanFu** [comment]
Sorry my bad. I added the method names to the .h file

**Comment by GabrielCartier** [comment]
@smileyborg any news on this?

**Comment by smileyborg** [comment]
Sorry - was waiting to hear back from @pronebird who opened similar issue #29. I also want to take a closer look at this and really think about the use cases here, I've just been really busy recently with things and haven't gotten a chance.

I'm always much more thoughtful about changes (including additions) to the public API, because as you know when you're providing a framework/library/SDK like this, once something is public it has to be supported and deprecated in a controlled fashion. So it's important to get it right from the start :)

**Comment by smileyborg** [comment]
You might be able to help my thinking by sharing the rationale behind exposing the two methods as you have done. In other words, how are you using them? Are there any others that might be useful or necessary too? Did you consider any other ways (e.g. other APIs) that these use cases could be addressed instead?

**Comment by pronebird** [comment]
Hi,

I thought I was clear about proposed changes.

It's important to give user instructions in case if location services are disabled system-wide or app-wide. Instructions can be different of course and in latter case you can take user directly to Settings.

Another use case that I have is, I don't spam user with authorization alerts on first try, instead I do it on action, e.g. on tap to button which supposedly should lead to location-related functionality / controller.

In original request #29 I also included a method called "shouldRequestAuthorization" which checks intermediate state when user didn't grant or reject access to location services for app.

Roughly my current flow looks as following when user taps on location button:

    if(![LocationManager locationServicesEnabled])
    {
         // show alert
    }
    else if([LocationManager shouldRequestAuthorization])
    {
       // request authorization
    }
    else if(![LocationManager authorizedForLocationServices])
    {
        // show alert
    }

`applicationLocationAuthorizationEnabled` is very long name :-)

**Comment by GabrielCartier** [comment]
I agree with @pronebird. This was basically our use case. The library would offer a better flexibility when it comes to knowing the authorization status of the user. It is quite important to properly indicate what is preventing the user from using the location services.


I agree with the  method name, also, if you feel like you should have a method to know if the user has ever been prompter, feel free to add it to the PR. 

Either way, I feel like those methods are only offering more flexibility with no downside. We also kept the old method to ensure legacy which is not bad anyway.

**Comment by smileyborg** [comment]
OK, thanks for the patience on this :)

Here's what I propose:

1. The following existing API on INTULocationManager will be **deprecated** for now, and removed in a future release:

        /** Returns YES if location services are enabled in the system settings, and the app has NOT been denied/restricted access. Returns NO otherwise. */
        @property (nonatomic, readonly) BOOL locationServicesAvailable __attribute__((deprecated));

2. The proposals in this PR (#28) and the related issue raised by @pronebird (#29) will be consolidated by adding a single new public API:

        /** Returns the current state of location services for this app, based on the system settings and user authorization status. */
        + (INTULocationServicesState)locationServicesState;

    This API is a class method (as opposed to a readonly property) because we don't need an instance of INTULocationManager to return the current state.

    Here is the definition of the return type `INTULocationServicesState`:

```
/** The possible states that location services can be in. */
typedef NS_ENUM(NSInteger, INTULocationServicesState) {
    /** User has already granted this app permissions to access location services, and they are enabled and ready for use by this app.
        Note: this state will be returned for both the "When In Use" and "Always" permission levels. */
    INTULocationServicesStateAvailable,
    /** User has not yet responded to the dialog that grants this app permission to access location services. */
    INTULocationServicesStateNotDetermined,
    /** User has explicitly denied this app permission to access location services. (The user can enable permissions again for this app from the system Settings app.) */
    INTULocationServicesStateDenied,
    /** User does not have ability to enable location services (e.g. parental controls, corporate policy, etc). */
    INTULocationServicesStateRestricted,
    /** User has turned off location services device-wide (for all apps) from the system Settings app. */
    INTULocationServicesStateDisabled
};
```

As I had previously suggested, this API/enum somewhat mirrors the `INTULocationStatus` one that is used when executing the block for a location request. The difference of course is that this `INTULocationServicesState` does not correspond to a specific location request and can be queried at any time (such as before even making the first location request).

I like this proposal for two main reasons:
 * it's simple, with just a single public API (as opposed to a few new methods that each return a BOOL)
 * it uses an enum to capture all the states, which makes it clear that they are mutually exclusive and that only one is possible at any given time

Please let me know if this addresses everything you have in mind, and if you have any suggestions for improvement. I'll get this checked in if all is good!

**Comment by GabrielCartier** [comment]
Agreed, good thinking. That will suits our needs.

**Comment by smileyborg** [comment]
Checked in, please give it a try! I will update the pod soon.

**Comment by pronebird** [comment]
Awesome, thanks @smileyborg!

**Pull request closed without merging**
