### PR TITLE
Updated Interface Builder Files for Example App

### PR DESCRIPTION
**Pull request by AdamBCo**
- Created Launch_Screen.storyboard to allow for example application to
conform to larger screen sizes.

- Added auto-layout and constraints to Main storyboard file to organize
interface.

### CODE REVIEW

**Comment by kristinathai** [comment]
Hi Adam, thanks for suggesting this. If you didn't see above, the build failed for this PR, so we can't merge it in yet.

More importantly, this change is likely to cause a merge conflict with #52. Given the significant changes in that PR, and the fact that it touches the core library (where these changes only impact the example app), I'd rather hold off on integrating this for now until that gets merged.

**Comment by lwdupont** [comment]
Hey @AdamBCo, sorry for the delay. I've volunteered to help keep these up to date. Still interested in merging this?

**Comment by AdamBCo** [comment]
Yeah sure! :)

**Comment by lwdupont** [comment]
Great, thanks. Can you fix up the pull request please with the latest source?

**Comment by lwdupont** [comment]
Hey @AdamBCo I was attempting to fix the merge conflicts, but with the storyboard file and Xcode project file, I'm always weary of attempt those. So I am going to close this pull request. If you want to redo it please let me know, otherwise I will fix up the files myself.

Appreciate your time and effort though. 👍

**Pull request closed without merging**
