### PR TITLE
Ability to subscribe to significant location changes.

### PR DESCRIPTION
**Pull request by ruslanskorb**
Hi guys!

Thank you for the cool library!
A little help from me :-]

Added ability to subscribe to significant location changes.
Also added some tests and an example.

### CODE REVIEW

**Comment by smileyborg** [comment]
Hi Ruslan,

I haven't had a chance to look closely at the changes, but it looks really awesome, thank you for submitting this PR! I especially appreciate that you have updated the unit tests alongside your changes.

I'd like to wait to merge this in until I (and any others interested) have some time to review it more thoroughly -- let me know if you have any urgency to get this merged. Otherwise I'll try to get it taken care of this week for sure.

Thanks again!!

**Comment by ruslanskorb** [comment]
Hi Tyler,

Do not rush. There is no urgency.
If you will have any suggestions or questions about the PR I'm ready for discussion.

Thanks!

**Comment by smileyborg** [comment]
Just wanted to let you know I haven't forgotten about this, reviewing the changes right now!

**Comment by smileyborg** [comment]
OK, finished reviewing everything. Overall, your changes are **fantastic** -- thank you very much for the contribution! Great job putting this together.

I made some very minor changes (see 592db7f) and merged this in. I would greatly appreciate it if you could try the latest on master (including my changes) and make sure everything is working great!

Thanks again Ruslan! I'm sure this enhancement will be very well received.

**Comment by ruslanskorb** [comment]
@smileyborg Thanks for reviewing and merging this! I have tried the latest on master. **Everything works well!** Special thanks for the changes that you've added, all of them are really necessary :-]

@prakashdonga8 You're welcome!

**Comment by smileyborg** [comment]
Glad to hear :) this will make it into the next release very soon. :beers:

**Pull request merged**
