### PR TITLE
Add Tests for the LocationManager

### PR DESCRIPTION
**Pull request by orta**
With @lazerwalker

We've added a base of tests around the INTULocationRequest and INTULocationManager classes. Our current plan of attack is to add some more coverage to the INTULocationManager, as well as add in Travis/Coveralls support for CI and code coverage metrics.

### CODE REVIEW

**Comment by orta** [comment]
Travis + Coveralls support is in. :+1:

**Comment by smileyborg** [comment]
Awesome!!! 👍 😄 Wasn't sure how difficult it would be to unit test this, definitely looking forward to checking out the details and merging this in. I'm traveling all day tomorrow but should be able to get to this on Monday.

Thanks for taking this on!

**Comment by orta** [comment]
oddly enough, after this I ended up needing a localtionmanger of sorts. Now I'm a library end user too.

**Comment by lazerwalker** [comment]
Haha, awesome.

**Comment by smileyborg** [comment]
Merged! Made a few small changes, most importantly removing the Test target from the Run/Build of the example project app target, to avoid forcing people to run `pod install` just to run the example app.

**Comment by smileyborg** [comment]
Thanks again, @orta and @lazerwalker. Everything is working great, except for the code coverage in Coveralls: https://coveralls.io/r/intuit/LocationManager

This is the first time I have used Slather + Coveralls. Running Slather locally on the Xcode project works fine:
```
$ slather coverage -s LocationManagerExample/LocationManagerExample.xcodeproj/
Slathering...
Source/INTULocationManager.m: 180 of 240 lines (75.00%)
Source/INTULocationRequest.m: 60 of 73 lines (82.19%)
Test Coverage: 76.68%
Slathered
```

However, something is failing when this runs on Travis, and as a result Coveralls get sent 0% coverage. Any ideas on this?

**Comment by orta** [comment]
Interesting, it looks like we got the same results: https://coveralls.io/r/orta/LocationManager

@marklarr any ideas?

**Comment by lazerwalker** [comment]
Also seeing that with https://coveralls.io/r/IntentKit/IntentKit – wonder how widespread it is.

**Comment by dasmer** [comment]
Same here: https://github.com/AlexDenisov/FrameAccessor/pull/17

**Comment by smileyborg** [comment]
@orta @lazerwalker @dasmer I was able to figure out what is going on. See: https://github.com/venmo/slather/issues/69#issuecomment-95366049

It seems like it would be a good idea to avoid using `script` to execute tests (as in the `.travis.yml` from this PR), and instead let Travis' do the default behavior of invoking `xctool`.

Was there any reason you guys were intentionally using `script` here?

**Comment by orta** [comment]
No strong reasoning, I use xcpretty in most places, easy to copy and paste working code from elsewhere.

**Comment by smileyborg** [comment]
OK, cool. `xcpretty` is nice, I agree. Using the Travis defaults instead of a custom script is also nice (for different reasons), so I think either way is fine. Obviously, will stick with this way for now since it is working with Slather.

**Pull request merged**
