### PR TITLE
Added Heading Support

### PR DESCRIPTION
**Pull request by irosenb**
Added `CLHeading` support. You can instantly get direction & location of the iPhone.

### CODE REVIEW

**Comment by smileyborg** [comment]
Hey Isaac, this is awesome! Love to see PRs.

I haven't looked closely at the changes yet, but it looks like these changes are based off an older state of the repo (before the recent changes for v2.0). If you're comfortable doing so, would you mind rebasing onto the latest from master? That will bring it up to date. Note that v2.0 had some significant changes about with a new subscription API, etc, so you might need to manually resolve some conflicts.

A few other comments:
* What is an example use case for making a one-time heading request? Unlike with the current location, I can only think of use cases where you'd want continuous heading updates (e.g. as part of the subscription API).
* It looks like some of the changes may have changed or broken the existing behavior around getting the current location...we'll need to make sure none of the existing functionality is broken before merging this in.
* In order to minimize impact to existing users, we'll need to maintain backwards compatibility with the existing public API. So that means we can't easily change the number of parameters in the block, for instance. Need to come up with a strategy for this before merging in.

Overall, very cool stuff, thanks again for the contribution!

**Comment by irosenb** [comment]
Hm, not sure how I didn't get the right version of the repo :confused:. 

I was making a camera app, and when it took a picture, I wanted to grab the location + direction someone was facing. Didn't make sense to always have the Heading. 

I did break the functionality. The problem is that you can't guarantee that the heading will be updated the same time as the location. So I moved `[self processLocationRequests];` over to the `didUpdateHeading` method. Obviously, this breaks the location functionality. 

Perhaps the heading could be an optional parameter? I'll look into it more…

**Comment by smileyborg** [comment]
You may have just forked it before the recent changes were committed.

As far as decoupling the location and heading functionality/APIs, how about having a separate request API and block type for the heading? So, if you wanted both, you would have to call the 2 APIs separately. But that seems sensible to me given that most people probably just want the location only, and don't want to wait for the heading since they come separately.

Another consideration: the current abstractions around accuracy/recency work well for location, but not heading. It would be nice to have a way to abstract how accurate the heading is (both when the user first requests a heading of at least a given accuracy, and when passing the heading back to the user).

**Comment by smileyborg** [comment]
Closing this for now, but please reopen or submit a new one if you get a chance to take care of the things mentioned above!

**Pull request closed without merging**
