### PR TITLE
Add framework for carthage

### PR DESCRIPTION
**Pull request by charlyliu**
I added a framework target and make all the headers in LocationManager group as public.

With this framework, everyone can also use Carthage to install it in their apps.

### CODE REVIEW

**Comment by smileyborg** [comment]
Hey @charlyliu,

Thank you very much for this PR! Carthage support is definitely something we want to add. I should be able to get around to reviewing this tomorrow and will merge it in as soon as that's done.

**Comment by charlyliu** [comment]
You're welcome. This project is wonderful. Hope I did it correctly the framework.

**Comment by smileyborg** [comment]
Overall this looks great! I am trying to make a few extra changes while merging this in to improve things even more, for example:

* Make the example app (target) consume the framework (target) -- this makes it easier to make sure that the framework target builds and works well
* Rename the Xcode project since it now contains more than just the example app (including this framework, as well as the unit tests)

Sorry for the delay, if there is any urgency I can merge this in for now and just make those improvements on top separately.

**Comment by smileyborg** [comment]
(I've already started doing this work, just some more Xcode project wrangling to do.)

**Comment by charlyliu** [comment]
Merge it whenever is better for you, I'm not using it right now but will use it in the future. If I use it before you merge it, I can use my fork as a temporary solution.

**Comment by smileyborg** [comment]
Thanks again for submitting this PR, and sorry for the delay! It's all merged in, as well as a number of other general cleanup and enhancements to the Xcode project. Please give the latest release a try with Carthage and make sure it's all working well!

**Pull request merged**
