### PR TITLE
Features/background location update

### PR DESCRIPTION
**Pull request by d4r1091**
I was facing the scenario within you have to modify the preset of Background Location updates even when you start with an authorization like "When In Use".
Whit this in mind, I just added the possibility by an entity, to modify this capability as well.
For my personal project I found it very useful and handy to manage.
Hope you appreciate,
Dario

### CODE REVIEW

**Comment by lwdupont** [comment]
@d4r1091 : I was finally looking at this with a coworker. In line 134 to 142 of INTULocationManager.m, there's code that will automatically set this based upon your info.plist entry for UIBackgroundModes. Apple's documentation suggests to me that even if you set allowsBackgroundLocationUpdates to true, without the correct entry in the info.plist your app won't get background updates. 

We don't understand why an app would ever want to set this if it's not going to work. 

I'm going to close this, but feel free to add a comment if you think that isn't the case or we missed something.

**Comment by d4r1091** [comment]
Hey @lwdupont sorry for the big delay :)
Basically, the reason why I added that method was because of my intention to enable the background notification updates only in some certain conditions.
i.e. in my app I've a "radar" function that aim to use the background location whether normally I set it to "when in use"

**Comment by lwdupont** [comment]
No worries on the delay, and yes, makes sense. Vs always on or always off. I'll review it one more time in the next few days, but seems reasonable to me. cc @eoghain

**Comment by eoghain** [comment]
I could do without all of the whitespace changes, but the actual code change makes sense to me.

**Comment by d4r1091** [comment]
Yeah sorry for the whitespaces...it's been a problem of indentation :) if you want I'll review adding only the needed lines

**Comment by lwdupont** [comment]
That'd be great @d4r1091, appreciate it.

**Pull request closed without merging**
