### PR TITLE
sharedInstance - send alloc call to [self class] to support singleton…

### PR DESCRIPTION
**Pull request by markedwardmurray**
…pattern in subclasses

Just a tiny tweak to better support subclassing in the singleton pattern. ( http://stackoverflow.com/a/15441482 ) 

Amazing framework, thank you.
~Mark

### CODE REVIEW

**Comment by 4Kicks** [comment]
@markedwardmurray Hey thanks for this pull request.  Just curious to get a better understanding of how/why this would be needed.  The link included in this pull request discusses a lot of the concerns around why subclassing would be necessary.  Would a Category not work in this case?

**Comment by markedwardmurray** [comment]
Hey @4Kicks , thanks for the reply. I subclassed in order to post a notification that the authorization status changed by using the `locationManager:didChangeAuthorizationStatus:` delegate method exposed in the `INTULocationManager+Internal.h` file. I had never subclassed a singleton before and discovered that stackoverflow discussion in the process, ensuring the subclass's singleton was initialized as the correct type and not the superclass's type (though I wasn't certain this would actually be a concern).

I'm not certain that this was really the best approach to try and in the meantime I've actually reverted my attempt to use INTULocationManager (though I've relied it on other projects). I wasn't able to fit it into what the codebase's existing custom LocationManager was already doing, oh well  ¯\_(ツ)_/¯

**Comment by vinner2112** [comment]
Dear friend! 

Here  are some interesting  facts you may  be interested  in, I think this information could  be  helpful, read  it here <http://pleasure.letsreadstuff.com/e4cdk>

All the best, vinner_2112

**Pull request closed without merging**
