### PR TITLE
refactoring example by google OC guideline

### PR DESCRIPTION
**Pull request by AndyChenW**

### CODE REVIEW

**Comment by AndyChenW** [comment]
@smileyborg 
1. code format as https://google-styleguide.googlecode.com/svn/trunk/objcguide.xml
2. remove some if else and duplication code by make them as data
3. stop indicator loading if force complete the request

and I want to do more as:
1. make the example project pod support
2. add test and CI for this project

**Comment by smileyborg** [comment]
Hi Andy,

First of all, thank you for taking the time to work on these changes, it's great to see contributions from the open source community!

I am traveling on a trip until next week, so I may not be able to review this more closely until I get back. But I did want to give you some high level feedback on these changes.

Overall the changes look very good quality. However, it looks like most of this is just style changes to switch to Google's open source style for Objective-C. While I certainly don't have anything against Google's style, it is just one of many valid styles, and it is not the style that the rest of this library has been written with. Generally speaking I find coding style to be very subjective. To me, it's much more important that code is written in a consistent style, regardless of which style that happens to be.

So as a result, I am not excited about making a bunch of changes primarily for the sake of adopting a new coding style. What is to keep someone else who prefers, for example, the New York Times Objective-C style over the Google one from coming and refactoring everything later on to match that? The code was already consistently styled, so any changes are a subjective improvement.

With that said, if there are objective changes or enhancements in here, I would be happy to review these to merge in. As I mentioned, I haven't yet had a chance to look closely through these, and I will let you know when I do.

As far as a Pod for the example project, I don't think that it makes very much sense. Pods are for dependencies and the example project should never be a dependency in another app. Using the `pod try INTULocationManager` command will let you easily get this example project anyways.

Tests and CI would be **fantastic** for this project. I think the difficulty will be figuring out how to test/mock the interaction with CLLocationManager.

Thanks again for taking the initiative on this work. Please let me know if this makes sense, and if you have any questions!

**Comment by AndyChenW** [comment]
1. about the coding style, I think google or apple will be both ok, you are right, I should follow this project's style.
2. this commit is too large that should be separated into server commits: coding style, refactoring if else, stop indicate loading after force complete etc.
3. about the example supported by cocoapods, you are right.
4. thanks so much, LocationManager is very good designed and inspired me a lot.

**Comment by smileyborg** [comment]
Great, if you want to try and separate out any changes in this PR that are not just style refactoring and submit those as a new PR that would be fantastic!

**Comment by smileyborg** [comment]
Closing this since #34 and #35 were opened instead.

**Pull request closed without merging**
